module.exports = {
  baidu: {
    languageList1: [
      { code: 'auto', name: '自动检测语言' },
      { code: 'zh', name: '简体中文' },
      { code: 'en', name: '英语' },
      { code: 'yue', name: '粤语' },
      { code: 'wyw', name: '文言文' },
      { code: 'jp', name: '日语' },
      { code: 'fra', name: '法语' },
      { code: 'spa', name: '西班牙语' },
      { code: 'th', name: '泰语' },
      { code: 'ara', name: '阿拉伯语' },
      { code: 'ru', name: '俄语' },
      { code: 'pt', name: '葡萄牙语' },
      { code: 'de', name: '德语' },
      { code: 'it', name: '意大利语' },
      { code: 'el', name: '希腊语' },
      { code: 'nl', name: '荷兰语' },
      { code: 'pl', name: '波兰语' },
      { code: 'bul', name: '保加利亚语' },
      { code: 'est', name: '爱沙尼亚语' },
      { code: 'dan', name: '丹麦语' },
      { code: 'fin', name: '芬兰语' },
      { code: 'cs', name: '捷克语' },
      { code: 'rom', name: '罗马尼亚语' },
      { code: 'slo', name: '斯洛文尼亚语' },
      { code: 'swe', name: '瑞典语' },
      { code: 'hu', name: '匈牙利语' },
      { code: 'cht', name: '繁体中文' },
      { code: 'vie', name: '越南语' }
    ],
    languageList2: [
      { code: 'zh', name: '简体中文' },
      { code: 'en', name: '英语' },
      { code: 'yue', name: '粤语' },
      { code: 'wyw', name: '文言文' },
      { code: 'jp', name: '日语' },
      { code: 'fra', name: '法语' },
      { code: 'spa', name: '西班牙语' },
      { code: 'th', name: '泰语' },
      { code: 'ara', name: '阿拉伯语' },
      { code: 'ru', name: '俄语' },
      { code: 'pt', name: '葡萄牙语' },
      { code: 'de', name: '德语' },
      { code: 'it', name: '意大利语' },
      { code: 'el', name: '希腊语' },
      { code: 'nl', name: '荷兰语' },
      { code: 'pl', name: '波兰语' },
      { code: 'bul', name: '保加利亚语' },
      { code: 'est', name: '爱沙尼亚语' },
      { code: 'dan', name: '丹麦语' },
      { code: 'fin', name: '芬兰语' },
      { code: 'cs', name: '捷克语' },
      { code: 'rom', name: '罗马尼亚语' },
      { code: 'slo', name: '斯洛文尼亚语' },
      { code: 'swe', name: '瑞典语' },
      { code: 'hu', name: '匈牙利语' },
      { code: 'cht', name: '繁体中文' },
      { code: 'vie', name: '越南语' }
    ]
  },
  tencent: {
    languageList1: [
      { code: 'auto', name: '自动识别语言' },
      { code: 'zh', name: '简体中文' },
      { code: 'zh-TW', name: '繁体中文' },
      { code: 'en', name: '英语' },
      { code: 'ja', name: '日语' },
      { code: 'ko', name: '韩语' },
      { code: 'fr', name: '法语' },
      { code: 'es', name: '西班牙语' },
      { code: 'it', name: '意大利语' },
      { code: 'de', name: '德语' },
      { code: 'tr', name: '土耳其语' },
      { code: 'ru', name: '俄语' },
      { code: 'pt', name: '葡萄牙语' },
      { code: 'vi', name: '越南语' },
      { code: 'id', name: '印尼语' },
      { code: 'th', name: '泰语' },
      { code: 'ms', name: '马来西亚语' },
      { code: 'ar', name: '阿拉伯语' },
      { code: 'hi', name: '印地语' }
    ],
    languageList2: [
      { code: 'zh', name: '简体中文' },
      { code: 'zh-TW', name: '繁体中文' },
      { code: 'en', name: '英语' },
      { code: 'ja', name: '日语' },
      { code: 'ko', name: '韩语' },
      { code: 'fr', name: '法语' },
      { code: 'es', name: '西班牙语' },
      { code: 'it', name: '意大利语' },
      { code: 'de', name: '德语' },
      { code: 'tr', name: '土耳其语' },
      { code: 'ru', name: '俄语' },
      { code: 'pt', name: '葡萄牙语' },
      { code: 'vi', name: '越南语' },
      { code: 'id', name: '印尼语' },
      { code: 'th', name: '泰语' },
      { code: 'ms', name: '马来西亚语' },
      { code: 'ar', name: '阿拉伯语' },
      { code: 'hi', name: '印地语' }
    ]
  }
};